name: Check prod pwd secret

on:
  workflow_dispatch:

jobs:
  check_pwd:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - name: Check if prod pwd equals 123
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          if [ "$SENTRY_DSN" = "123" ]; then
            echo "Secret pwd is correct."
          else
            echo "Secret pwd is NOT correct."
            exit 1
          fi
